# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with the official Go image as the build environment
FROM golang:1.23 AS builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the go.mod and go.sum files to the workspace
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the rest of the source code
COPY . .

# Build the Go app
RUN go build -o mcp-tavily-search ./cmd

# Start a new stage from scratch
FROM debian:bookworm-slim

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/mcp-tavily-search .

# Command to run the executable
ENTRYPOINT ["/app/mcp-tavily-search"]
